### ISSUE TITLE
Vivaldi 安装后无法显示

### ISSUE THREAD

**Issue by aozaki-kuro** [bambooGHT/channel-script#1]
您好，近期因为 ASMR 主播纷纷从 YT 出逃到 Niconico FanClub，于是在各路自动化程序都失效(?)的情况下找到了您的 userscript

最开始使用您的 https://gist.github.com/bambooGHT/8f5e7902b9420c9cdbf35033b30b9072 这个版本的脚本，在 Vivaldi 上以 TamperMonkey 安装，可以正常显示及下载

安装本 repo 中的版本后，在各页面则无法显示。
例如：
<img width="1250" alt="image" src="https://github.com/bambooGHT/channel-script/assets/28428951/191fe649-43b6-4ab1-9ac3-94861c781d7f">
<img width="1235" alt="image" src="https://github.com/bambooGHT/channel-script/assets/28428951/e54803c4-f0ab-4ef4-a9eb-09416a9acb09">

我的环境：
Vivaldi	6.8.3381.46 (Stable channel) (arm64) 
修订版本：fc048ddc979dd4b5812491cce07da57059e0bbae
操作系统：macOS Version 14.5 (Build 23F79)
JavaScript：V8 12.6.228.21

安装使用 Tampermonkey，已尝试清除 Cookies 及使用无痕模式（关闭其他插件）。

~~早上着急上班，还没测试 Chrome 的情况~~

**Comment by bambooGHT** [comment]
旧的已经不维护了,使用现在的脚本需要登录,另外,需要开启扩展的开发者模式 `工具>扩展>开发者模式`

**Comment by aozaki-kuro** [comment]
注册登陆后测试正常使用，再次感谢！
