### ISSUE TITLE
可以新增頻道嗎(鬼花)

### ISSUE THREAD

**Issue by ianias** [bambooGHT/channel-script#3]
https://malice-kibana.com/live/smNE7cp9kVE5S4JxWxCPVAyV

**Comment by bambooGHT** [comment]
这个我上次更新就已经添加了

**Comment by ianias** [comment]
诶，哪怎麼沒出現其他都會有的那個
![螢幕擷取畫面 2024-08-19 210159](https://github.com/user-attachments/assets/9a119b73-5077-4e02-9243-c770322eb641)

**Comment by bambooGHT** [comment]
时间是20号,不是今天

**Comment by ianias** [comment]
沒開播之前不是也會有嗎
只是沒有play而已
