### ISSUE TITLE
按钮消失了

### ISSUE THREAD

**Issue by AkG023** [bambooGHT/channel-script#6]
大佬，这个作品之前（大概一周前）可以直接通过脚本看的，但是现在没有按钮了，是脚本没法使用了吗？
我看下了现在还有按钮的视频，都是需要一时无料的部分才有按钮，和这个有关吗？
点进去现在没有按钮的视频，返回再点进现在有按钮的视频， 有按钮的视频的按钮也消失了不能播放和下载了
https://nicochannel.jp/kumonoue_yumemi/video/smCzaHHENvdSk4two8e6G6UV

**Comment by bambooGHT** [comment]
是的,已经加上了用户验证,不能白嫖完全会员限定的了

**Comment by clmmu** [comment]
請問現在連開頭免費&直播的播放按鈕都消失了，會修正嗎?

**Comment by bambooGHT** [comment]
> 請問現在連開頭免費&直播的播放按鈕都消失了，會修正嗎?

修了
